"""Generate a recruiter/client-friendly HTML report from CloudLens JSON output."""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime

from jinja2 import Template


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CloudLens Report — {{ company }}</title>
<style>
body{font-family:Arial,sans-serif;margin:0;background:#f4f6f8;color:#17202a}main{max-width:980px;margin:auto;background:white;padding:42px}h1{margin-bottom:4px}.muted{color:#607080}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.card{border:1px solid #dfe5eb;border-radius:10px;padding:16px}.num{font-size:28px;font-weight:700}.finding{border-left:4px solid #b7c2cc;padding:14px 18px;margin:16px 0;background:#fafbfc}.critical{border-color:#a61b1b}.high{border-color:#d35400}.medium{border-color:#d4ac0d}.low{border-color:#2e86c1}.badge{font-size:12px;text-transform:uppercase;font-weight:700}.rec{margin-top:10px;padding:10px;background:#eef3f7}.small{font-size:12px}.footer{margin-top:40px;border-top:1px solid #ddd;padding-top:16px}.errors{background:#fff7e6;padding:12px;border-radius:8px}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}main{padding:20px}}
</style>
</head>
<body><main>
<h1>CloudLens AWS Audit</h1>
<p class="muted">{{ company }} · Generated {{ generated }}{% if auditor %} · Auditor: {{ auditor }}{% endif %}</p>
<div class="grid">
  <div class="card"><div class="num">{{ score }}</div><div>Health score / 100</div></div>
  <div class="card"><div class="num">{{ findings|length }}</div><div>Total findings</div></div>
  <div class="card"><div class="num">{{ high_count }}</div><div>High / critical</div></div>
  <div class="card"><div class="num">R$ {{ savings }}</div><div>Illustrative monthly savings</div></div>
</div>
<h2>Executive summary</h2>
<p>The audit reviewed read-only configuration metadata in {{ regions|length }} AWS region(s). Findings are prioritized by severity and paired with remediation guidance. Cost figures are illustrative estimates.</p>
<h2>Findings</h2>
{% if findings %}
{% for f in findings %}
<section class="finding {{ f.severity }}">
  <div class="badge">{{ f.severity }} · {{ f.category }}</div>
  <h3>{{ f.title }}</h3>
  <p class="small muted">{{ f.resource_type }} · {{ f.resource_id }} · {{ f.region }}</p>
  <p>{{ f.description }}</p>
  <div class="rec"><strong>Recommendation:</strong> {{ f.recommendation }}</div>
</section>
{% endfor %}
{% else %}<p>No findings were recorded in the supplied audit result.</p>{% endif %}
{% if errors %}<h2>Audit limitations</h2><div class="errors"><ul>{% for e in errors %}<li><strong>{{ e.check }}:</strong> {{ e.message }}</li>{% endfor %}</ul></div>{% endif %}
<div class="footer small muted">CloudLens is a portfolio/learning project and is not a substitute for a formal compliance assessment, penetration test, or production cloud-security platform.</div>
</main></body></html>"""


def health_score(findings: list[dict]) -> int:
    weights = {"critical": 15, "high": 8, "medium": 3, "low": 1}
    return max(0, 100 - sum(weights.get(f.get("severity", "low"), 1) for f in findings))


def slug(text: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_").lower()
    return value or "report"


def generate(json_path: str, company: str, auditor: str | None, output_dir: str | None) -> str:
    with open(json_path, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    findings = sorted(
        data.get("findings", []),
        key=lambda f: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(f.get("severity"), 4),
    )
    context = {
        "company": company,
        "auditor": auditor,
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "regions": data.get("regions", []),
        "findings": findings,
        "errors": data.get("errors", []),
        "score": health_score(findings),
        "high_count": sum(f.get("severity") in {"critical", "high"} for f in findings),
        "savings": f"{float(data.get('total_estimated_savings_brl', 0) or 0):,.2f}",
    }
    html = Template(TEMPLATE).render(**context)

    base = output_dir or os.path.dirname(os.path.abspath(json_path))
    os.makedirs(base, exist_ok=True)
    path = os.path.join(base, f"CloudLens_Report_{slug(company)}.html")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(html)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a CloudLens HTML report")
    parser.add_argument("json_file", help="JSON generated by audit.py")
    parser.add_argument("--company", default="Demo Company")
    parser.add_argument("--auditor-name")
    parser.add_argument("--output-dir")
    args = parser.parse_args()
    path = generate(args.json_file, args.company, args.auditor_name, args.output_dir)
    print(f"HTML report: {path}")


if __name__ == "__main__":
    main()
